config/routes.rb
Rails.application.routes.draw do
  root "pages#top"
  get '/signup', to: 'users#new'
  get '/top', to: 'pages_#post'
  # get '/post', to: 'pages#post'
  get '/about', to: 'pages#about'
  get '/my_page', to: 'pages#my_page'
  get '/search', to: 'searches#search'

  # get '/posts', to: "posts#new"
  # post '/posts', to: "posts#create"

  get '/login', to: 'sessions#new'          #restアーキテクチャ　get => new
  post '/login', to: 'sessions#create'      #restアーキテクチャ　post => create
  delete '/logout', to: 'sessions#destroy'   #restアーキテクチャ　delete => destroy
  # ↑手動でリソースを作る場合（ログイン機能は、new,create,destroyしか使わないため、手動で作成した。）

  # ↓自動でリソースを作った場合
  resources :users   #railsのレストフルアーキテクチャが使えるようになる。（url '/users'で参照可能になる）
                      # get => showアクションに対応づけられる。
                      # usersコントローラーのshowアクションにルーティング
                      # つまり、resourcesは、自動でget,post,update,delete...を自動で対応づけを作ってくれる。
  resources :posts do  # => 使える、アクション・httpメソッドの限定。こうする事で、create、destroyアクションに対応したpostとdeleteメソッドが使える。
    # resources :favorites, only: [:create, :destroy]
    post '/favorite', to: 'favorites#create', as: 'create_favorite'
    delete '/favorite', to: 'favorites#destroy', as: 'destroy_favorite'
  end


end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
    validates :user_id, presence: true
    validates :post_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :post_params
  def create

    # 投稿したユーザーはいいねできない
    # if current_user.id != @post.user_id
    #   @favorite = Favorite.create(user_id: current_user.id, post_id: @post.id)
      
    # else

    #   redirect_to request.referrer
      
    # end

    # 投稿したユーザーもいいねできる
    @favorite = Favorite.create(user_id: current_user.id, post_id: @post.id)
  end

  def destroy

    # 投稿したユーザーはいいねできない

    # if current_user.id != @post.user_id
    #   @favorite = Favorite.find_by(user_id: current_user.id, post_id: @post.id)
    #   @favorite.destroy

    # else
    #   redirect_to request.referrer
      
    # end


    # 投稿したユーザーもいいねできる
    @favorite = Favorite.find_by(user_id: current_user.id, post_id: @post.id)
    @favorite.destroy
    
  end

  private
  def post_params
    @post = Post.find(params[:post_id])
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if favorite?(post.id) %>
    お気に入り：<%= link_to "★", post_destroy_favorite_path(post), method: :DELETE, remote: true %>
<% else %>
    お気に入り：<%= link_to "☆", post_create_favorite_path(post), method: :POST, remote: true %>
<% end %>
<%= post.favorites.count%>

app/views/favorites/create.js.erb
    <%#= byebug %>
$('#favorite_button<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post})%>");

app/views/favorites/destroy.js.erb
$('#favorite_button<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post})%>");