config/routes.rb
Rails.application.routes.draw do
  root "pages#top"
  get '/signup', to: 'users#new'
  get '/top', to: 'pages_#post'
  # get '/post', to: 'pages#post'
  get '/about', to: 'pages#about'
  get '/my_page', to: 'pages#my_page'
  get '/search', to: 'searches#search'

  # get '/posts', to: "posts#new"
  # post '/posts', to: "posts#create"

  get '/login', to: 'sessions#new'          #restアーキテクチャ　get => new
  post '/login', to: 'sessions#create'      #restアーキテクチャ　post => create
  delete '/logout', to: 'sessions#destroy'   #restアーキテクチャ　delete => destroy
  # ↑手動でリソースを作る場合（ログイン機能は、new,create,destroyしか使わないため、手動で作成した。）

  # ↓自動でリソースを作った場合
  resources :users   #railsのレストフルアーキテクチャが使えるようになる。（url '/users'で参照可能になる）
                      # get => showアクションに対応づけられる。
                      # usersコントローラーのshowアクションにルーティング
                      # つまり、resourcesは、自動でget,post,update,delete...を自動で対応づけを作ってくれる。
  resources :posts do  # => 使える、アクション・httpメソッドの限定。こうする事で、create、destroyアクションに対応したpostとdeleteメソッドが使える。
    # resources :favorites, only: [:create, :destroy]
    post '/favorite', to: 'favorites#create', as: 'create_favorite'
    delete '/favorite', to: 'favorites#destroy', as: 'destroy_favorite'
  end


end

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <div class="navbar-brand"><%= link_to "福祉.net", root_path %></div>
            <ul class="navbar navbar-right">
                <li class="navbar-text"><%= link_to "使い方", about_path %></li>
                <%# <li class="navbar-text">= link_to "ユーザー（一覧）", users_path</li> %>
                <li class="navbar-text"><%=  link_to "投稿一覧", root_path %></li>
            <% if logged_in? %>
                <li class="navbar-text"><%= link_to "記事の作成", new_post_path %></li>
                <li class="navbar-text"><%= link_to "#{current_user.name}_page", user_path(current_user) %></li>
                <li class="navbar-text"><%= @current_user.name %>でログイン中</li>
                <li class="navbar-text"><%= link_to "ログアウト", logout_path, method: :delete %></li>
            <% else %>
                <li class="navbar-text"><%= link_to "新規登録", signup_path %></li>
                <li class="navbar-text"><%= link_to "ログイン", login_path %></li>
            <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# ↓full_titleメソッド => cf)application_helper  %>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container text-center">
      <% flash.each do |message_type, message| %> <%# flash変数(users_controllerで定義)は、ハッシュを持つ。
                                                  railsコンソールで、flash変数の中身に代入して、確認してみる。 %>
        <div class="flash"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.devlopment? %>  <!-- デバッグ　-->
    </div>
  </body>
</html>